### ISSUE TITLE
Missing library libwayland-client

### ISSUE THREAD

**Issue by wielorzeczownik** [martadinata666/dockerized#1]
**Description**
After the last update, I get an error with a missing library in the `reactive-resume` image.

**Error**
```
2022-07-02 08:47:20,039 INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libwayland-client.so.0                           ║
╚══════════════════════════════════════════════════════╝
    at PrinterService.onModuleInit (/home/debian/reactiveresume/server/dist/printer/printer.service.js:28:61)
    at MapIterator.iteratee (/home/debian/reactiveresume/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
    at MapIterator.next (/home/debian/reactiveresume/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/map.js:13:39)
    at IteratorWithOperators.next (/home/debian/reactiveresume/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/iterate.js:21:28)
    at IteratorWithOperators.toArray (/home/debian/reactiveresume/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/iterate.js:180:22)
    at callOperator (/home/debian/reactiveresume/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)
    at callModuleInitHook (/home/debian/reactiveresume/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)
    at NestApplication.callInitHook (/home/debian/reactiveresume/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/nest-application-context.js:178:50)
    at async NestApplication.init (/home/debian/reactiveresume/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/nest-application.js:96:9)
    at async NestApplication.listen (/home/debian/reactiveresume/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/nest-application.js:158:33)
    at async bootstrap (/home/debian/reactiveresume/server/dist/main.js:19:5) {
  name: 'Error'
}

d
/home/debian/reactiveresume/server:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @reactive-resume/server@ start:prod: `node dist/main`
Exit status 1
2022-07-02 08:47:21,490 INFO exited: server (exit status 1; not expected)
```

**Comment by martadinata666** [comment]
Thanks for the report, will update the depedencies soon 👍🏼
